# Generated by Django 3.1.5 on 2021-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_original', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
