# Generated by Django 3.1.5 on 2021-01-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='myshows.country'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='slogan',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='episode',
            name='synopsis',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=3000)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.show')),
            ],
        ),
    ]
