# Generated by Django 3.1.5 on 2021-01-23 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0002_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('UN', 'Неизвестно'), ('UK', 'Великобритания')], default='UN', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='broadcast_status',
            field=models.CharField(choices=[('UKN', 'Неизвестно'), ('C/E', 'Отменено/Завершено'), ('TBD', 'Будет определено')], default='UKN', max_length=3),
        ),
        migrations.AddField(
            model_name='show',
            name='categories',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='show',
            name='country',
            field=models.CharField(default='UN', max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='ended',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_voted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='kinopoisk_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='kinopoisk_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='kinopoisk_voted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='myshows_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='myshows_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='myshows_voted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='myshows_watching',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='runtime_one',
            field=models.DurationField(default=datetime.timedelta()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='runtime_total',
            field=models.DurationField(default=datetime.timedelta()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='seasons_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='started',
            field=models.DateField(default=datetime.date(2021, 1, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='tvrage_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(to='myshows.Genre'),
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myshows.network'),
        ),
    ]
