# Generated by Django 3.1.5 on 2021-01-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0003_auto_20210123_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(to='myshows.Tag'),
        ),
    ]
