# Generated by Django 3.1.5 on 2021-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0004_auto_20210123_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='name_original',
            new_name='title_original',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RemoveField(
            model_name='show',
            name='categories',
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.CharField(choices=[('film', 'Кино'), ('cart', 'Мультфильм'), ('anim', 'Аниме'), ('anit', 'Анимация'), ('thea', 'Театр'), ('tv', 'ТВ шоу')], default='film', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='runtime_total_str',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(choices=[('show', 'Сериал'), ('full', 'Полнометражный'), ('shrt', 'Короткометражный')], default='show', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='runtime_total',
            field=models.DurationField(null=True),
        ),
    ]
