# Generated by Django 3.1.5 on 2021-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0004_auto_20210131_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='animated_poster',
            field=models.FileField(null=True, upload_to='animated_posters/'),
        ),
    ]
