# Generated by Django 3.1.5 on 2021-01-23 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myshows', '0005_auto_20210123_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('foreword', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('video', models.CharField(max_length=5000, null=True)),
                ('category', models.CharField(choices=[('trailer', 'Трейлер'), ('anonsy', 'Анонс')], max_length=20)),
                ('tags', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='network',
            name='country',
            field=models.CharField(choices=[('UN', 'Неизвестно'), ('UK', 'Великобритания'), ('US', 'США'), ('JP', 'Япония'), ('CA', 'Канада'), ('NO', 'Норвегия'), ('RU', 'Россия'), ('IT', 'Италия'), ('AU', 'Австралия'), ('SU', 'СССР'), ('FR', 'Франция'), ('SE', 'Швеция'), ('UA', 'Украина'), ('AR', 'Аргентина'), ('KR', 'Южная Корея'), ('LV', 'Латвия'), ('TR', 'Турция'), ('DE', 'Германия'), ('BR', 'Бразилия')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='show',
            name='broadcast_status',
            field=models.CharField(choices=[('UKN', 'Неизвестно'), ('C/E', 'Отменено/Завершено'), ('TBD', 'Будет определено'), ('AIR', 'Сериал продолжается'), ('NEW', 'Новый сериал'), ('IND', 'В производстве')], default='UKN', max_length=3),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.article')),
            ],
        ),
    ]
