# Generated by Django 3.1.5 on 2021-02-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0006_auto_20210201_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_html', models.TextField()),
                ('type', models.CharField(choices=[('trailer', 'Трейлер'), ('teaser', 'Тизер'), ('fragment', 'Фрагмент')], max_length=10)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.show')),
            ],
        ),
    ]
