# Generated by Django 3.1.5 on 2021-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0006_auto_20210124_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('trailer', 'Трейлер'), ('anonsy', 'Анонс'), ('articles', 'Статья'), ('blog', 'Блог')], max_length=20),
        ),
        migrations.AddField(
            model_name='show',
            name='country_new',
            field=models.ManyToManyField(to='myshows.CountryModel'),
        ),
        migrations.AddField(
            model_name='network',
            name='country_new',
            field=models.ForeignKey(default=1, on_delete=models.deletion.PROTECT, to='myshows.countrymodel'),
            preserve_default=False,
        ),
    ]
