# Generated by Django 3.1.5 on 2021-01-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0007_auto_20210124_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='country',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='country_new',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='network',
            name='country',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='country_new',
            new_name='country',
        ),
        migrations.RenameModel(
            old_name='CountryModel',
            new_name='Country',
        ),
    ]
