# Generated by Django 3.1.5 on 2021-02-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myshows', '0007_showvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PER', 'Персонаж'), ('LOC', 'Место'), ('ORG', 'Организация'), ('PRC', 'Процент'), ('DAT', 'Дата'), ('CAR', 'Число'), ('MIS', 'Разное')], max_length=3)),
            ],
            options={
                'verbose_name': 'NamedEntity',
                'verbose_name_plural': 'NamedEntities',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='description_marked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NamedEntityOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('named_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.namedentity')),
            ],
        ),
    ]
