# Generated by Django 3.1.5 on 2021-01-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0008_auto_20210124_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('air_date', models.DateTimeField()),
                ('is_special', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('episodes_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('trailer', models.TextField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.show')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshows.season'),
        ),
    ]
