# Generated by Django 3.1.5 on 2021-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0009_auto_20210225_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedentityoccurrence',
            name='occurrence_context',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, to='myshows.Genre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myshows.Tag'),
        ),
    ]
