# Generated by Django 3.1.5 on 2021-01-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0009_auto_20210125_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='runtime_total_str',
        ),
    ]
