# Generated by Django 3.1.5 on 2021-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0010_auto_20210226_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namedentityoccurrence',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='namedentityoccurrence',
            name='occurrence_context',
        ),
        migrations.AddField(
            model_name='namedentityoccurrence',
            name='window_left',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='namedentityoccurrence',
            name='window_right',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='namedentityoccurrence',
            name='window_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
