# Generated by Django 3.1.5 on 2021-03-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0011_auto_20210227_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedentityoccurrence',
            name='window_left',
        ),
        migrations.RemoveField(
            model_name='namedentityoccurrence',
            name='window_right',
        ),
        migrations.RemoveField(
            model_name='namedentityoccurrence',
            name='window_text',
        ),
        migrations.AddField(
            model_name='namedentityoccurrence',
            name='position_end',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namedentityoccurrence',
            name='position_start',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='show',
            name='description_marked',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_marked',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='string_marked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description_marked',
        ),
        migrations.AlterField(
            model_name='show',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
