# Generated by Django 3.1.5 on 2021-01-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0012_auto_20210125_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
