# Generated by Django 3.1.5 on 2021-01-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshows', '0013_auto_20210125_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeimage',
            name='image',
            field=models.ImageField(upload_to='episode'),
        ),
    ]
